<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Callie McCormack" />
    <meta name="description" content="Describe your website">
    <link rel="shortcut icon" type="image/x-icon" href="/img/favicon.ico">
    <title>Project 2</title>
    <meta name="generator" content="Hugo 0.70.0" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="/css/main.css" />
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,400,200bold,400old" />
    
    <!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->

    
  </head>

  <body>
    <div id="wrap">

      
      <nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/"><i class="fa fa-home"></i></a>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar">
      <ul class="nav navbar-nav navbar-right">
      
        
        <li><a href="/blog/">BLOG</a></li>
        
        <li><a href="/projects/">PROJECTS</a></li>
        
        <li><a href="/resume.pdf">RESUME</a></li>
        
      
      </ul>
    </div>
  </div>
</nav>

      
      <div class="container">
        <div class="blog-post">
          <h3>
            <strong><a href="/project2.utf8/">Project 2</a></strong>
          </h3>
        </div>
        <div class="blog-title">
          <h4>
          January 1, 0001
            &nbsp;&nbsp;
            
          </h4>
        </div>
        <div class="panel panel-default">
          <div class="panel-body">
            <div class="blogpost">
              <div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">Suicide <span style="color:#f92672">&lt;-</span> <span style="color:#a6e22e">read.csv</span>(<span style="color:#e6db74">&#34;who_suicide_statistics.csv&#34;</span>)
Suicide<span style="color:#f92672">&lt;-</span> Suicide <span style="color:#f92672">%&gt;%</span> <span style="color:#a6e22e">drop_na</span>()
<span style="color:#e6db74">&#39;%!in%&#39;</span> <span style="color:#f92672">&lt;-</span> <span style="color:#a6e22e">function</span>(x,y)<span style="color:#f92672">!</span>(<span style="color:#e6db74">&#39;%in%&#39;</span>(x,y))
Suicide<span style="color:#f92672">$</span>year <span style="color:#f92672">&lt;-</span> <span style="color:#a6e22e">as.factor</span>(Suicide<span style="color:#f92672">$</span>year)
<span style="color:#a6e22e">set.seed</span>(<span style="color:#ae81ff">1234</span>)
Suicidedata <span style="color:#f92672">&lt;-</span> Suicide<span style="color:#f92672">%&gt;%</span><span style="color:#a6e22e">mutate</span>(y<span style="color:#f92672">=</span><span style="color:#a6e22e">ifelse</span>(sex<span style="color:#f92672">==</span><span style="color:#e6db74">&#34;female&#34;</span>, <span style="color:#ae81ff">1</span>, <span style="color:#ae81ff">0</span>))
</code></pre></div><h2 id="introduction">Introduction</h2>
<p>I found the WHO suicide statistics on the Kaggle website. The dataset was made using the WHO mortality database online tool, and covers the year 1979-2016. 141 countries are covered in the dataset, with 6 groupings of age from 5-75 in ten year intervals. Sex is a factor with two levels of male and females which I used as the binary variable. Suicides_no is a numeric variable that list the number of suicides, while population lists the number of people in the country, with a one to one ratio. Since some countries didn&rsquo;t measure suicide numbers, I omitted the rows that have NA&rsquo;s. When the NA&rsquo;s were omitted, there were 36,060 observations.</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#75715e">#Manova</span>


covmats <span style="color:#f92672">&lt;-</span> Suicide<span style="color:#f92672">%&gt;%</span> <span style="color:#a6e22e">group_by</span>(age) <span style="color:#f92672">%&gt;%</span> <span style="color:#a6e22e">do</span>(covs<span style="color:#f92672">=</span><span style="color:#a6e22e">cov</span>(.[5<span style="color:#f92672">:</span><span style="color:#ae81ff">6</span>]))
<span style="color:#a6e22e">for</span>(i in <span style="color:#ae81ff">1</span><span style="color:#f92672">:</span><span style="color:#ae81ff">6</span>){<span style="color:#a6e22e">print</span>(<span style="color:#a6e22e">as.character</span>(covmats<span style="color:#f92672">$</span>age[i])); <span style="color:#a6e22e">print</span>(covmats<span style="color:#f92672">$</span>covs[i])}
</code></pre></div><pre><code>## [1] &quot;15-24 years&quot;
## [[1]]
##              suicides_no   population
## suicides_no     250871.9 1.120415e+09
## population  1120415034.6 1.153350e+13
## 
## [1] &quot;25-34 years&quot;
## [[1]]
##              suicides_no   population
## suicides_no     554531.7 1.549635e+09
## population  1549635345.3 1.073301e+13
## 
## [1] &quot;35-54 years&quot;
## [[1]]
##             suicides_no   population
## suicides_no     2430411 5.756611e+09
## population   5756611047 3.137593e+13
## 
## [1] &quot;5-14 years&quot;
## [[1]]
##              suicides_no   population
## suicides_no 8.216003e+02 6.547980e+07
## population  6.547980e+07 1.145551e+13
## 
## [1] &quot;55-74 years&quot;
## [[1]]
##              suicides_no   population
## suicides_no     903940.3 2.441789e+09
## population  2441789157.9 1.283195e+13
## 
## [1] &quot;75+ years&quot;
## [[1]]
##             suicides_no   population
## suicides_no    115684.4 2.839754e+08
## population  283975366.5 1.472035e+12
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">man <span style="color:#f92672">&lt;-</span> <span style="color:#a6e22e">manova</span>(<span style="color:#a6e22e">cbind</span>(suicides_no, population)<span style="color:#f92672">~</span>age, data<span style="color:#f92672">=</span>Suicide)
<span style="color:#a6e22e">summary</span>(man)
</code></pre></div><pre><code>## Df Pillai approx F num Df den Df Pr(&gt;F)
## age 5 0.060836 226.22 10 72108 &lt; 2.2e-16 ***
## Residuals 36054
## ---
## Signif. codes: 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1
' ' 1
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#a6e22e">summary.aov</span>(man) 
</code></pre></div><pre><code>## Response suicides_no :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## age 5 8.1188e+08 162375464 228.9 &lt; 2.2e-16 ***
## Residuals 36054 2.5576e+10 709377
## ---
## Signif. codes: 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1
' ' 1
##
## Response population :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## age 5 1.5938e+16 3.1875e+15 240.87 &lt; 2.2e-16 ***
## Residuals 36054 4.7713e+17 1.3234e+13
## ---
## Signif. codes: 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1
' ' 1
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#a6e22e">pairwise.t.test</span>(Suicide<span style="color:#f92672">$</span>suicides_no, Suicide<span style="color:#f92672">$</span>age, p.adj<span style="color:#f92672">=</span><span style="color:#e6db74">&#34;none&#34;</span>)
</code></pre></div><pre><code>##
## Pairwise comparisons using t tests with pooled SD
##
## data: Suicide$suicides_no and Suicide$age
##
## 15-24 years 25-34 years 35-54 years 5-14 years 55-74
years
## 25-34 years 3.1e-05 - - - -
## 35-54 years &lt; 2e-16 &lt; 2e-16 - - -
## 5-14 years &lt; 2e-16 &lt; 2e-16 &lt; 2e-16 - -
## 55-74 years &lt; 2e-16 1.2e-10 &lt; 2e-16 &lt; 2e-16 -
## 75+ years 0.018 6.2e-11 &lt; 2e-16 5.6e-14 &lt; 2e-16
##
## P value adjustment method: none
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#a6e22e">pairwise.t.test</span>(Suicide<span style="color:#f92672">$</span>population,Suicide<span style="color:#f92672">$</span>age, p.adj<span style="color:#f92672">=</span><span style="color:#e6db74">&#34;none&#34;</span>)
</code></pre></div><pre><code>##
## Pairwise comparisons using t tests with pooled SD
##
## data: Suicide$population and Suicide$age
##
## 15-24 years 25-34 years 35-54 years 5-14 years 55-74
years
## 25-34 years 0.31 - - - -
## 35-54 years &lt;2e-16 &lt;2e-16 - - -
## 5-14 years 0.73 0.50 &lt;2e-16 - -
## 55-74 years 0.40 0.86 &lt;2e-16 0.61 -
## 75+ years &lt;2e-16 &lt;2e-16 &lt;2e-16 &lt;2e-16 &lt;2e-16
##
## P value adjustment method: none
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#ae81ff">1</span> <span style="color:#f92672">-</span> (<span style="color:#ae81ff">.95</span>)^33
</code></pre></div><pre><code>## [1] 0.8159741
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#ae81ff">.05</span><span style="color:#f92672">/</span><span style="color:#ae81ff">33</span>
</code></pre></div><pre><code>## [1] 0.001515152
</code></pre><p>There are many assumptions for a MANOVA, but the assumption of multivariate normality is met since there are more than 25 observations per group. The assumption of homogeneity for co-variances is not met since the 5-14 age group co-variance matrix seems to vary from the other age groups.1 MANOVA test was run, 2 ANOVA&rsquo;s were run, and 30 t tests were run (33 tests in total). The probability of a type one error is 81.6%, and the adjusted significance level is .0015. With the new significance level,5-14 year olds differ from every age group in suicide number,15-24 year olds differ from every age group except for 75+ ages, 25-34 year olds suicide numbers differ significantly from every other age group, the 35-54 year olds differ from every age group, 55-75 year olds differ from every age group, and 75+ age group differs from every group except 15-24 year olds. In population numbers, 75+ year olds differ from every age group, and 35-54 year olds differ from every age group. All other age groups do not differ from each other.</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">Suicide<span style="color:#f92672">%&gt;%</span><span style="color:#a6e22e">group_by</span>(sex)<span style="color:#f92672">%&gt;%</span>
  <span style="color:#a6e22e">summarize</span>(means<span style="color:#f92672">=</span><span style="color:#a6e22e">mean</span>(suicides_no))<span style="color:#f92672">%&gt;%</span>
  <span style="color:#a6e22e">summarize</span>(`mean_diff:`<span style="color:#f92672">=</span><span style="color:#a6e22e">diff</span>(means))
</code></pre></div><!-- raw HTML omitted -->
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">rand_dist <span style="color:#f92672">&lt;-</span> <span style="color:#a6e22e">vector</span>()

<span style="color:#a6e22e">for</span>(i in <span style="color:#ae81ff">1</span><span style="color:#f92672">:</span><span style="color:#ae81ff">5000</span>){
  new <span style="color:#f92672">&lt;-</span> <span style="color:#a6e22e">data.frame</span>(Suicides<span style="color:#f92672">=</span><span style="color:#a6e22e">sample</span>(Suicide<span style="color:#f92672">$</span>suicides_no), Sex<span style="color:#f92672">=</span>Suicide<span style="color:#f92672">$</span>sex)
  rand_dist[i]<span style="color:#f92672">&lt;-</span><span style="color:#a6e22e">mean</span>(new[new<span style="color:#f92672">$</span>Sex<span style="color:#f92672">==</span><span style="color:#e6db74">&#34;female&#34;</span>,]<span style="color:#f92672">$</span>Suicides)<span style="color:#f92672">-</span>
                <span style="color:#a6e22e">mean</span>(new[new<span style="color:#f92672">$</span>Sex<span style="color:#f92672">==</span><span style="color:#e6db74">&#34;male&#34;</span>,]<span style="color:#f92672">$</span>Suicides)} 


{<span style="color:#a6e22e">hist</span>(rand_dist,main<span style="color:#f92672">=</span><span style="color:#e6db74">&#34;&#34;</span>,ylab<span style="color:#f92672">=</span><span style="color:#e6db74">&#34;&#34;</span>); <span style="color:#a6e22e">abline</span>(v<span style="color:#f92672">=</span><span style="color:#ae81ff">233.493</span>,col<span style="color:#f92672">=</span><span style="color:#e6db74">&#34;red&#34;</span>)}
</code></pre></div><p><!-- raw HTML omitted --></p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#a6e22e">mean</span>(rand_dist<span style="color:#f92672">&gt;</span> <span style="color:#ae81ff">233.493</span> <span style="color:#f92672">|</span> rand_dist<span style="color:#f92672">&lt;</span> <span style="color:#ae81ff">-233.493</span>)
</code></pre></div><pre><code>## [1] 0
</code></pre><p>The null hypothesis is that there is no mean difference in suicide numbers between sexes. The results of the randomization test show that we can reject the null hypothesis that there is no difference in suicide numbers between sexes. The calculated mean difference (233) is much higher than the null distribution so the test statistic isn&rsquo;t visible on the histogram of the null distribution.</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#75715e">#Linear Regression Model</span>

Suicidedata<span style="color:#f92672">$</span>population_c <span style="color:#f92672">&lt;-</span> Suicide<span style="color:#f92672">$</span>population<span style="color:#f92672">-</span> <span style="color:#a6e22e">mean</span>(Suicide<span style="color:#f92672">$</span>population)
Suicidedata<span style="color:#f92672">$</span>suicides_no_c <span style="color:#f92672">&lt;-</span> Suicide<span style="color:#f92672">$</span>suicides_no <span style="color:#f92672">-</span> <span style="color:#a6e22e">mean</span>(Suicide<span style="color:#f92672">$</span>suicides_no)


fit <span style="color:#f92672">&lt;-</span> <span style="color:#a6e22e">lm</span>(suicides_no_c <span style="color:#f92672">~</span> population_c<span style="color:#f92672">+</span>sex<span style="color:#f92672">+</span>sex<span style="color:#f92672">:</span>population_c, data<span style="color:#f92672">=</span>Suicidedata)
<span style="color:#a6e22e">summary</span>(fit)
</code></pre></div><pre><code>##
## Call:
## lm(formula = suicides_no_c ~ population_c + sex +
sex:population_c,
## data = Suicidedata)
##
## Residuals:
## Min 1Q Median 3Q Max
## -4548.5 -26.1 5.6 34.0 18091.9
##
## Coefficients:
## Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) -1.193e+02 4.437e+00 -26.89 &lt;2e-16 ***
## population_c 6.388e-05 1.181e-06 54.07 &lt;2e-16 ***
## sexmale 2.450e+02 6.275e+00 39.05 &lt;2e-16 ***
## population_c:sexmale 1.609e-04 1.698e-06 94.77 &lt;2e-16
***
## ---
## Signif. codes: 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1
' ' 1
##
## Residual standard error: 595.7 on 36056 degrees of
freedom
## Multiple R-squared: 0.5151, Adjusted R-squared: 0.5151
## F-statistic: 1.277e+04 on 3 and 36056 DF, p-value: &lt;
2.2e-16
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">Suicidedata <span style="color:#f92672">%&gt;%</span> <span style="color:#a6e22e">ggplot</span>() <span style="color:#f92672">+</span> <span style="color:#a6e22e">geom_point</span>(<span style="color:#a6e22e">aes</span>(x<span style="color:#f92672">=</span>population_c, y<span style="color:#f92672">=</span>suicides_no_c, color<span style="color:#f92672">=</span>sex),
alpha<span style="color:#f92672">=</span><span style="color:#ae81ff">.2</span>) <span style="color:#f92672">+</span>  <span style="color:#a6e22e">geom_smooth</span>(method <span style="color:#f92672">=</span> <span style="color:#e6db74">&#34;lm&#34;</span>, se <span style="color:#f92672">=</span> <span style="color:#66d9ef">FALSE</span>, <span style="color:#a6e22e">aes</span>(x<span style="color:#f92672">=</span>population_c,
y<span style="color:#f92672">=</span>suicides_no_c, color<span style="color:#f92672">=</span>sex))
</code></pre></div><p><!-- raw HTML omitted --></p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">resids <span style="color:#f92672">&lt;-</span> fit<span style="color:#f92672">$</span>residuals

<span style="color:#a6e22e">ks.test</span>(resids, <span style="color:#e6db74">&#34;pnorm&#34;</span>,mean<span style="color:#f92672">=</span><span style="color:#ae81ff">0</span>, <span style="color:#a6e22e">sd</span>(resids))
</code></pre></div><pre><code>## 
## 	One-sample Kolmogorov-Smirnov test
## 
## data:  resids
## D = 0.32633, p-value &lt; 2.2e-16
## alternative hypothesis: two-sided
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#a6e22e">bptest</span>(fit)
</code></pre></div><pre><code>## 
## 	studentized Breusch-Pagan test
## 
## data:  fit
## BP = 3582, df = 3, p-value &lt; 2.2e-16
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#a6e22e">coeftest</span>(fit, vcov <span style="color:#f92672">=</span> <span style="color:#a6e22e">vcovHC</span>(fit))
</code></pre></div><pre><code>##
## t test of coefficients:
##
## Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) -1.1930e+02 1.5785e+00 -75.578 &lt; 2.2e-16 ***
## population_c 6.3882e-05 1.5063e-06 42.411 &lt; 2.2e-16 ***
## sexmale 2.4504e+02 6.4994e+00 37.702 &lt; 2.2e-16 ***
## population_c:sexmale 1.6090e-04 6.7643e-06 23.786 &lt;
2.2e-16 ***
## ---
## Signif. codes: 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1
' ' 1
</code></pre><p>The predicted suicide number for females of an average population is -119.3. Controlling for sex, for every one unit increase in population, the number of suicides increases by 6.3883-5. Controlling for population, being male increases the number of suicides by 245. The slope for population on suicides number for males is 1.609e-4 greater. The linear regression does not pass the assumption of normality via the KS test and fails the assumption of homoskedacity using the BP test. Using robust standard errors, all coefficients are still significant. The variables tested explain 51.51% of the variation in suicide numbers. The standard error increases for every variable/interaction and decreased for the intercept. The probability increases for everything, but is still significant.</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#75715e">#Boostraped Standard Errors</span>


samp_distn<span style="color:#f92672">&lt;-</span><span style="color:#a6e22e">replicate</span>(<span style="color:#ae81ff">5000</span>, {  
            boot_dat <span style="color:#f92672">&lt;-</span> <span style="color:#a6e22e">sample_frac</span>(Suicidedata, replace<span style="color:#f92672">=</span>T) 
            fit <span style="color:#f92672">&lt;-</span> <span style="color:#a6e22e">lm</span>(suicides_no_c<span style="color:#f92672">~</span>population_c<span style="color:#f92672">+</span>sex<span style="color:#f92672">+</span>sex<span style="color:#f92672">:</span>population_c,
data<span style="color:#f92672">=</span>boot_dat)  
            <span style="color:#a6e22e">coef</span>(fit) }) 

samp_distn <span style="color:#f92672">%&gt;%</span> t <span style="color:#f92672">%&gt;%</span> as.data.frame <span style="color:#f92672">%&gt;%</span> <span style="color:#a6e22e">summarize_all</span>(sd)
</code></pre></div><!-- raw HTML omitted -->
<p>With Bootstrapped standard errors,the standard errors are in between the original standard errors and the robust standard errors. The probability is slightly higher than the original regression, but is still significant.</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#75715e">#Logistic Regression</span>


logisticfit <span style="color:#f92672">&lt;-</span> <span style="color:#a6e22e">glm</span>(y<span style="color:#f92672">~</span>population_c<span style="color:#f92672">+</span>suicides_no_c,data<span style="color:#f92672">=</span>Suicidedata, family<span style="color:#f92672">=</span><span style="color:#e6db74">&#34;binomial&#34;</span>)
<span style="color:#a6e22e">coeftest</span>(logisticfit)
</code></pre></div><pre><code>##
## z test of coefficients:
##
## Estimate Std. Error z value Pr(&gt;|z|)
## (Intercept) -1.0709e-01 1.1979e-02 -8.9398 &lt; 2.2e-16 ***
## population_c 2.0878e-07 6.4189e-09 32.5261 &lt; 2.2e-16 ***
## suicides_no_c -2.1717e-03 6.1858e-05 -35.1074 &lt; 2.2e-16
***
## ---
## Signif. codes: 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1
' ' 1
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#a6e22e">exp</span>(<span style="color:#a6e22e">coeftest</span>(logisticfit))
</code></pre></div><pre><code>## 
## z test of coefficients:
## 
##               Estimate Std. Error    z value Pr(&gt;|z|)
## (Intercept)    0.89844    1.01205 1.0000e-04        1
## population_c   1.00000    1.00000 1.3363e+14        1
## suicides_no_c  0.99783    1.00006 0.0000e+00        1
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">probs <span style="color:#f92672">&lt;-</span> <span style="color:#a6e22e">predict</span>(logisticfit, type <span style="color:#f92672">=</span> <span style="color:#e6db74">&#34;response&#34;</span>)
<span style="color:#a6e22e">table</span>(predict<span style="color:#f92672">=</span><span style="color:#a6e22e">as.numeric</span>(probs<span style="color:#f92672">&gt;</span><span style="color:#ae81ff">.5</span>), truth<span style="color:#f92672">=</span>Suicidedata<span style="color:#f92672">$</span>y) <span style="color:#f92672">%&gt;%</span> <span style="color:#a6e22e">addmargins</span>()
</code></pre></div><pre><code>##        truth
## predict     0     1   Sum
##     0    8490  2250 10740
##     1    9540 15780 25320
##     Sum 18030 18030 36060
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#a6e22e">class_diag</span>(probs, Suicidedata<span style="color:#f92672">$</span>y)
</code></pre></div><!-- raw HTML omitted -->
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">Suicidedata<span style="color:#f92672">$</span>logit <span style="color:#f92672">&lt;-</span><span style="color:#a6e22e">predict</span>(logisticfit, type<span style="color:#f92672">=</span><span style="color:#e6db74">&#34;link&#34;</span>)

<span style="color:#a6e22e">ggplot</span>(Suicidedata,<span style="color:#a6e22e">aes</span>(logit, color<span style="color:#f92672">=</span>sex, fill<span style="color:#f92672">=</span>sex))<span style="color:#f92672">+</span><span style="color:#a6e22e">geom_density</span>(alpha<span style="color:#f92672">=</span><span style="color:#ae81ff">.3</span>)<span style="color:#f92672">+</span>
<span style="color:#a6e22e">geom_vline</span>(xintercept<span style="color:#f92672">=</span><span style="color:#ae81ff">0</span>,lty<span style="color:#f92672">=</span><span style="color:#ae81ff">2</span>)<span style="color:#f92672">+</span><span style="color:#a6e22e">xlim</span>(<span style="color:#ae81ff">-.1</span>,<span style="color:#ae81ff">.1</span>) <span style="color:#f92672">+</span> <span style="color:#a6e22e">geom_rug</span>()
</code></pre></div><p><!-- raw HTML omitted --></p>
<p>The odds of being female in a mean population with a mean number of suicides is .8944. Controlling for suicide number, for every one unit increase in population, the odds of the being female increases by a factor of 1. Controlling for population, for every one unit increase in suicide number the odds of being female decreases by a factor of .9978. The AUC is .733 which means it is a fair model, with the specificity being .47 and sensitivity .875.</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">ROCplot<span style="color:#f92672">&lt;-</span><span style="color:#a6e22e">ggplot</span>(Suicidedata) <span style="color:#f92672">+</span> <span style="color:#a6e22e">geom_roc</span>(<span style="color:#a6e22e">aes</span>(d<span style="color:#f92672">=</span>y, m<span style="color:#f92672">=</span>probs), n.cuts<span style="color:#f92672">=</span><span style="color:#ae81ff">0</span>)
ROCplot
</code></pre></div><p><!-- raw HTML omitted --></p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#a6e22e">calc_auc</span>(ROCplot)
</code></pre></div><!-- raw HTML omitted -->
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">k<span style="color:#f92672">=</span><span style="color:#ae81ff">10</span>

data1 <span style="color:#f92672">&lt;-</span> Suicidedata <span style="color:#f92672">%&gt;%</span> <span style="color:#a6e22e">sample_frac</span>()
folds <span style="color:#f92672">&lt;-</span> <span style="color:#a6e22e">ntile</span>(<span style="color:#ae81ff">1</span><span style="color:#f92672">:</span><span style="color:#a6e22e">nrow</span>(data1), n<span style="color:#f92672">=</span><span style="color:#ae81ff">10</span>)

diags<span style="color:#f92672">&lt;-</span><span style="color:#66d9ef">NULL</span> 

<span style="color:#a6e22e">for</span>(i in <span style="color:#ae81ff">1</span><span style="color:#f92672">:</span>k){  
     train <span style="color:#f92672">&lt;-</span> data1[folds<span style="color:#f92672">!=</span>i,]
     test <span style="color:#f92672">&lt;-</span> data1[folds<span style="color:#f92672">==</span>i,] 
     truth <span style="color:#f92672">&lt;-</span> test<span style="color:#f92672">$</span>y
     fit <span style="color:#f92672">&lt;-</span> <span style="color:#a6e22e">glm</span>(y<span style="color:#f92672">~</span> population<span style="color:#f92672">+</span>suicides_no, data<span style="color:#f92672">=</span>train, family<span style="color:#f92672">=</span><span style="color:#e6db74">&#34;binomial&#34;</span>) 
     probs <span style="color:#f92672">&lt;-</span> <span style="color:#a6e22e">predict</span>(fit, newdata<span style="color:#f92672">=</span>test, type<span style="color:#f92672">=</span><span style="color:#e6db74">&#34;response&#34;</span>) 
     diags<span style="color:#f92672">&lt;-</span><span style="color:#a6e22e">rbind</span>(diags,<span style="color:#a6e22e">class_diag</span>(probs,truth)) 
     } 
<span style="color:#a6e22e">summarize_all</span>(diags, mean)
</code></pre></div><!-- raw HTML omitted -->
<p>The AUC from the ROC plot is slightly higher than the AUC from the class_diag function, but is still a fair model.The average AUC from the 10-fold CV is slightly lower than the one from the ROC plot and the AUC from the class_diag function.</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#75715e">#Lasso Regression</span>

y <span style="color:#f92672">&lt;-</span> <span style="color:#a6e22e">as.matrix</span>(Suicide<span style="color:#f92672">$</span>sex)
x <span style="color:#f92672">&lt;-</span> <span style="color:#a6e22e">model.matrix</span>(sex<span style="color:#f92672">~</span><span style="color:#ae81ff">-1+.</span>, data<span style="color:#f92672">=</span>Suicide, na.action<span style="color:#f92672">=</span>na.omit)




cv <span style="color:#f92672">&lt;-</span> <span style="color:#a6e22e">cv.glmnet</span>(x,y, family<span style="color:#f92672">=</span><span style="color:#e6db74">&#34;binomial&#34;</span>)

lasso <span style="color:#f92672">&lt;-</span> <span style="color:#a6e22e">glmnet</span>(x,y, family <span style="color:#f92672">=</span> <span style="color:#e6db74">&#34;binomial&#34;</span>, lambda <span style="color:#f92672">=</span> cv<span style="color:#f92672">$</span>lambda.1se)

c<span style="color:#f92672">&lt;-</span><span style="color:#a6e22e">coef</span>(lasso)

inds<span style="color:#f92672">&lt;-</span><span style="color:#a6e22e">which</span>(c<span style="color:#f92672">!=</span><span style="color:#ae81ff">0</span>)
variables<span style="color:#f92672">&lt;-</span><span style="color:#a6e22e">row.names</span>(c)[inds]
variables<span style="color:#f92672">&lt;-</span>variables[variables <span style="color:#f92672">%!in%</span> <span style="color:#e6db74">&#39;(Intercept)&#39;</span>]


variables<span style="color:#f92672">&lt;-</span><span style="color:#a6e22e">str_remove</span>(variables, <span style="color:#e6db74">&#34;country&#34;</span>)
variables<span style="color:#f92672">&lt;-</span><span style="color:#a6e22e">str_remove</span>(variables, <span style="color:#e6db74">&#34;age&#34;</span>)

variables
</code></pre></div><pre><code>## [1] &quot;Australia&quot; &quot;Austria&quot;
## [3] &quot;Azerbaijan&quot; &quot;Belarus&quot;
## [5] &quot;Belgium&quot; &quot;Brazil&quot;
## [7] &quot;Bulgaria&quot; &quot;Canada&quot;
## [9] &quot;Colombia&quot; &quot;Croatia&quot;
## [11] &quot;Cuba&quot; &quot;Czech Republic&quot;
## [13] &quot;Ecuador&quot; &quot;Egypt&quot;
## [15] &quot;Finland&quot; &quot;France&quot;
## [17] &quot;Germany&quot; &quot;Greece&quot;
## [19] &quot;Guatemala&quot; &quot;Hungary&quot;
## [21] &quot;Iran (Islamic Rep of)&quot; &quot;Italy&quot;
## [23] &quot;Japan&quot; &quot;Kazakhstan&quot;
## [25] &quot;Latvia&quot; &quot;Lithuania&quot;
## [27] &quot;Mexico&quot; &quot;Philippines&quot;
## [29] &quot;Poland&quot; &quot;Republic of Korea&quot;
## [31] &quot;Romania&quot; &quot;Russian Federation&quot;
## [33] &quot;Serbia&quot; &quot;South Africa&quot;
## [35] &quot;Spain&quot; &quot;Sri Lanka&quot;
## [37] &quot;Sweden&quot; &quot;Switzerland&quot;
## [39] &quot;Thailand&quot; &quot;Turkey&quot;
## [41] &quot;Ukraine&quot; &quot;United Kingdom&quot;
## [43] &quot;Venezuela (Bolivarian Republic of)&quot; &quot;25-34 years&quot;
## [45] &quot;35-54 years&quot; &quot;5-14 years&quot;
## [47] &quot;55-74 years&quot; &quot;75+ years&quot;
## [49] &quot;suicides_no&quot; &quot;population&quot;
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">Suicidewide<span style="color:#f92672">&lt;-</span>Suicide<span style="color:#f92672">%&gt;%</span> <span style="color:#a6e22e">pivot_wider</span>(names_from <span style="color:#f92672">=</span> country, values_from <span style="color:#f92672">=</span> country,
values_fill <span style="color:#f92672">=</span> <span style="color:#a6e22e">list</span>(country<span style="color:#f92672">=</span><span style="color:#ae81ff">0</span>),
values_fn <span style="color:#f92672">=</span> <span style="color:#a6e22e">list</span>(country <span style="color:#f92672">=</span> <span style="color:#f92672">~+</span>(<span style="color:#a6e22e">as.logical</span>(<span style="color:#a6e22e">length</span>(.))))) <span style="color:#f92672">%&gt;%</span> <span style="color:#a6e22e">pivot_wider</span>(names_from<span style="color:#f92672">=</span> age, values_from <span style="color:#f92672">=</span> age, values_fill <span style="color:#f92672">=</span> <span style="color:#a6e22e">list</span>(age<span style="color:#f92672">=</span><span style="color:#ae81ff">0</span>),values_fn <span style="color:#f92672">=</span> <span style="color:#a6e22e">list</span>(age <span style="color:#f92672">=</span> <span style="color:#f92672">~+</span>(<span style="color:#a6e22e">as.logical</span>(<span style="color:#a6e22e">length</span>(.))))) <span style="color:#f92672">%&gt;%</span> <span style="color:#a6e22e">select</span>(<span style="color:#a6e22e">one_of</span>(variables), population, suicides_no,sex)

k<span style="color:#f92672">=</span><span style="color:#ae81ff">10</span>
suicidedat <span style="color:#f92672">&lt;-</span> Suicidewide<span style="color:#a6e22e">[sample</span>(<span style="color:#a6e22e">nrow</span>(Suicidewide)),]
folds<span style="color:#f92672">&lt;-</span><span style="color:#a6e22e">cut</span>(<span style="color:#a6e22e">seq</span>(<span style="color:#ae81ff">1</span><span style="color:#f92672">:</span><span style="color:#a6e22e">nrow</span>(Suicidewide)),breaks<span style="color:#f92672">=</span>k,labels<span style="color:#f92672">=</span>F)

diags <span style="color:#f92672">&lt;-</span> <span style="color:#66d9ef">NULL</span>

<span style="color:#a6e22e">for</span>(i in <span style="color:#ae81ff">1</span><span style="color:#f92672">:</span>k){
  train<span style="color:#f92672">&lt;-</span>suicidedat[folds<span style="color:#f92672">!=</span>i,]
  test <span style="color:#f92672">&lt;-</span> suicidedat[folds<span style="color:#f92672">==</span>i,]
  truth <span style="color:#f92672">&lt;-</span>test<span style="color:#f92672">$</span>sex
  
  fit <span style="color:#f92672">&lt;-</span> <span style="color:#a6e22e">glm</span>(sex<span style="color:#f92672">~</span>., data<span style="color:#f92672">=</span>train, family <span style="color:#f92672">=</span> <span style="color:#e6db74">&#34;binomial&#34;</span>)
  probs <span style="color:#f92672">&lt;-</span> <span style="color:#a6e22e">predict</span>(fit, newdata <span style="color:#f92672">=</span> test, type<span style="color:#f92672">=</span><span style="color:#e6db74">&#34;response&#34;</span>)
  
  diags <span style="color:#f92672">&lt;-</span> <span style="color:#a6e22e">rbind</span>(diags, <span style="color:#a6e22e">class_diag</span>(probs, truth))
}

diags <span style="color:#f92672">%&gt;%</span> <span style="color:#a6e22e">summarize_all</span>(mean)
</code></pre></div><!-- raw HTML omitted -->
<p>When I ran the lasso, 56 variables were retained including population, suicides_no, every age group except 15-24, and 49 different countries. The AUC from the 10-fold CV is the highest calculated compared to my logistic regression, but is only a little higher and is still only a fair model.</p>

              <hr>
              <div class="related-posts">
                <h5>Related Posts</h5>
                
              </div>
            </div>
          </div>
          <hr>
        <div class="disqus">
  <div id="disqus_thread"></div>
  <script type="text/javascript">

    (function() {
      
      
      if (window.location.hostname == "localhost")
        return;

      var disqus_shortname = '';
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
  </script>
  <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  <a href="http://disqus.com/" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
</div>
        </div>
      </div>
      
    </div>

    
    <footer>
  <div id="footer">
    <div class="container">
      <p class="text-muted">&copy; All rights reserved. Powered by <a href="https://gohugo.io/">Hugo</a> and
      <a href="http://www.github.com/nurlansu/hugo-sustain/">sustain</a> with ♥</p>
    </div>
  </div>
</footer>
<div class="footer"></div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="/js/docs.min.js"></script>
<script src="/js/main.js"></script>

<script src="/js/ie10-viewport-bug-workaround.js"></script>


    
  </body>
</html>
