---
title: "Untitled"
author: "Callie McCormack"
date: "5/15/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

EDUCATION
	
The University of Texas at Austin, Austin, TX      			                                                                                      05/2021  
Bachelor of Science in Biology: Genetics and Genomics
GPA: 3.97
Certification in Pre-Health Professions for Science Majors (18 hours)
Relevant Coursework: Genetics, Lab Experience in Genetics

EXPERIENCE 

UT Department of Physics, Austin, TX   				     	                                                      02/2019 - Present
Student Assistant											
•	Prepared rooms for student labs
•	Distributed lab materials to students
•	Assisted lab professors with a multitude of requests

PANERA BREAD, Lewisville, TX									          05/2018- 08/2018
Retail Hourly Associate
•	Problem solved issues on the line
•	Assisted in food production
•	Ensured quality and accuracy

ACTIVITIES & LEADERSHIP 
Crisis Text Line, New York, NY								                          10/2019- Present
Crisis Counselor
•	Underwent a 30-hour training program 
•	Helped people in crisis calm down
•	Safety planned with suicidal texters to keep them safe

Whole Woman’s Health, Austin, TX							                         09/2018- 02/2019
Patient Escort
•	Escorted patients to and from the clinic
•	Manned the front desk and checked in patients
•	Created charts for patients

Youth and Family Counseling, Lewisville, TX							       05/2018- 08/2018
Volunteer Office Assistant
•	Implemented a paperless intake system
•	Organized clients in a practice management system
•	Rescheduled clients/fielded calls

HONORS AND AWARDS 

•	CNS Second Year Excellence Award
•	College Scholar 
•	University Honors 
•	Unrestricted Presidential Endowed Scholar
